eldirectoriomx/urls.py
from django.contrib import admin
from django.urls import re_path, include 
from apps.registro.views import index, vista_login, vista_logout, CharData, resultados, detalle, filtrado_dentistas, filtrado_hoteles, filtrado_agencias, filtrado_restaurantes, filtro_estado_giro, registro_view, listado_participantes
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    re_path(r'^admin/',include('admin_honeypot.urls', namespace="admin_honeypot")),
    re_path(r'^admin_mx/', admin.site.urls),
    re_path(r'^$', index, name="index"),
    re_path(r'^registro/', registro_view, name="registro"),
    re_path(r'^participantes/', listado_participantes, name="participantes"),
    re_path(r'^dentistas/', filtrado_dentistas, name="dentistas"),
    re_path(r'^hoteles/', filtrado_hoteles, name="hoteles"),
    re_path(r'^agencias/', filtrado_agencias, name="agencias"),
    re_path(r'^restaurantes/', filtrado_restaurantes, name="restaurantes"),
    re_path(r'^resultados/(?P<pk>\d+)/$', detalle, name="resultados"),
    re_path(r'^resultados/(?P<pk_estado>\d+)/(?P<pk_categoria>\d+)/$', filtro_estado_giro, name="resfil"),
    re_path(r'^data/', CharData.as_view()),
    re_path(r'^login/', vista_login, name="login" ),
    re_path(r'^logout/',vista_logout,name='logout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/registro/models.py
from django.db import models
from datetime import datetime
from django.core.exceptions import ValidationError
# Create your models here.

class Estados(models.Model):
    nombre = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Estado'
        verbose_name_plural = 'Estados'

    
    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'categoría'
        verbose_name_plural = 'categorías'

    def __str__(self):
        return self.nombre


class Empresas(models.Model):
    nombre = models.CharField(max_length=70,  help_text="Aquí ingresa el nombre de la empresa", verbose_name="Nombre")
    email = models.EmailField(help_text="Aquí ingresa el email de la empresa", blank=True)
    telefono = models.CharField(max_length=30, help_text="Aquí ingresa el teléfono de la empresa",verbose_name="Teléfono" )
    servicios = models.TextField(max_length=300,help_text="Aquí ingresa los servicios de la empresa")
    imagen = models.ImageField()
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE, verbose_name="Categoría")
    red_social = models.CharField(max_length=200, blank=True, help_text="Aquí ingresa la red social de la empresa")
    cp = models.CharField(max_length=10,  help_text="Código Postal", verbose_name="Código Postal")
    estado = models.ForeignKey(Estados,on_delete=models.CASCADE)
    municipio = models.CharField(max_length=30,  help_text="Municipio")
    colonia = models.CharField(max_length=20,  help_text="Colonia")
    calle = models.TextField(max_length=200,  help_text="Calle")
    noext = models.CharField(max_length=30,  help_text="No. Exterior", verbose_name="No. Exterior")
    latitud = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    longitud = models.DecimalField(max_digits=9, decimal_places=6, null=True, blank=True)
    created = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'empresa'
        verbose_name_plural = 'empresas'

    def __str__(self):
        return str(self.id)+ '.- ' + self.nombre

def validate_image(imagen):
    file_size = imagen.file.size
    # limit_kb = 150
    # if file_size > limit_kb * 1024:
    #     raise ValidationError("Max size of file is %s KB" % limit)

    limit_mb = 3
    if file_size > limit_mb * 1024 * 1024:
       raise ValidationError("Max size of file is %s MB" % limit_mb)

class Participantes(models.Model):
    nombre = models.CharField(max_length=100,  help_text="Aquí ingresa el nombre", verbose_name="Nombre", blank=True)
    telefono = models.CharField(max_length=30, unique=True, help_text="Aquí ingresa el teléfono",verbose_name="Teléfono", blank=True)
    telefono2 = models.CharField(max_length=30, help_text="Aquí ingresa el teléfono 2",verbose_name="Teléfono 2", blank=True)
    email = models.EmailField(help_text="Aquí ingresa el email del participante", blank=True)
    imagen = models.ImageField(blank=True, validators=[validate_image])
    red_social = models.CharField(max_length=200, blank=True, help_text="Aquí ingresa su red social")
    estado = models.ForeignKey(Estados,on_delete=models.CASCADE)
    municipio = models.CharField(max_length=30,  help_text="Municipio", blank=True)
    colonia = models.CharField(max_length=200,  help_text="Colonia", blank=True)
    num_votos = models.IntegerField(default=0,blank=True)

    class Meta:
        verbose_name = 'participante'
        verbose_name_plural = 'participantes'

    def __str__(self):
        return str(self.id)+ '.- ' + self.nombre

templates/usuarios/detalle.html
{%extends 'base/base.html'%}
{% load staticfiles %}

{%block extrastatic%}

<style>
#llegar{
    background-color: rgb(251, 202, 17);
}
body {
  overflow-x: hidden;
}

#page-content-wrapper {
  min-width: 100vw;
}


#categori{
    color:rgb(39, 117, 148);
}
/* www.proyecto24.org
www.nacionalfinanciera.com.mx */
  #page-content-wrapper {
    min-width: 0;
    width: 100%;
  }

  #wrapper.toggled #sidebar-wrapper {
    margin-left: -15rem;
  }
#card{
  border: rgb(251, 202, 17) 5px solid;
}

#map {
        height: 400px;  /* The height is 400 pixels */
        width: 100%;  /* The width is the width of the web page */
       }
</style>
 <script src='https://npmcdn.com/@turf/turf/turf.min.js'></script>
 <script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
 <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.js'></script>
 <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css' rel='stylesheet' />
 <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.2/mapbox-gl-directions.js"></script>
  <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.2/mapbox-gl-directions.css" type="text/css"/>

{%endblock%}



{%block content%}
<div class="loader"></div>
<!-- Page Content -->
<div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              
            </ul>
          </div>
        </nav>
        <br>
        <br>
        <br>
    
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                  
                </div>
                <div class="col-md-8">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <div{% if message.tags == "success" %} class="alert alert-success"
                      {%else%}
                      class="alert alert-danger"
                      {% endif %}>
                      {{ message }}</div>
                        {% endfor %}
                    </ul>
                  {% endif %}
                </div>
                <div class="col-md-2">
                    
                </div>
            </div>	
                    <br>
                    <br>
            

                     <div class="card" id="card" style="width: 80%;height: 10%; left:10%; right: 10%;">
                        <div class="card-body">
                          <h5 class="card-title">{{empresa.nombre}}</h5>
                          <p class="card-text">{{empresa.calle|upper}} #{{empresa.noext|upper}}, {{empresa.colonia|upper}}, {{empresa.municipio|upper}}, {{empresa.estado|upper}}, C.P.{{empresa.cp}}</p>
                          <p class="card-text"><i class="fa fa-phone"></i> {{empresa.telefono}}</p>
                          <p class="card-text"><i class="fa fa-envelope"></i> {{empresa.email}}</p>
                          <p class="card-text">SERVICIOS: {{empresa.servicios|upper}}</p>
                          <a href="{{empresa.red_social}}"> <i class="fa fa-facebook-square"></i> {{empresa.nombre}}</a>
                          <p id="categori" class="card-text">{{empresa.categoria|upper}}</p>
                          <br>
                          
                        </div>
                        <img src="{{empresa.imagen.url}}" width="100%" height="100%" class="card-img-top" alt="...">
                        <div class="card-body">
                            <p class="card-text"><i class="fa fa-map-marker"></i> Indicaciones para uso del GPS:</p>
                            <p class="card-text">1.-Seleccione el origen <b>A</b> haciendo click en el mapa o ingresando dirección.</p>
                            <p class="card-text">2.-Seleccione el destino <b>B</b> haciendo click en el mapa o ingresando dirección.</p>
                        </div>
                        
                        
                        <div id="mapid" style="border: 3px solid rgb(10, 2, 114);width: 100%; height: 600px;"></div>
                        <script>
                        // var json_long = JSON.parse('{{ json_long | escapejs }}');
                        // var json_lat = JSON.parse('{{ json_lat | escapejs }}');
                        // console.log(json_lat);
                      
                        mapboxgl.accessToken = 'pk.eyJ1IjoiYW50b25pb3NhbGFpY2VzIiwiYSI6ImNqdXN5a256MjAyZnc0ZG5ybGptcXkxcG4ifQ.H0JQcmfgxKoqkYUrJ9OdAw';
                          
                          // Initialize a map
                          var map = new mapboxgl.Map({
                            container: 'mapid', // container id
                            style: 'mapbox://styles/mapbox/streets-v10', // stylesheet location
                            center: [-108.7957497,25.747628], // starting position
                            zoom: 8 // starting zoom
                          });
                          map.addControl(

                          me = new mapboxgl.GeolocateControl({
                          positionOptions: {
                          enableHighAccuracy: true
                          },
                          trackUserLocation: true
                          })
                          );
                          // Add zoom and rotation controls to the map.
                          map.addControl(new mapboxgl.NavigationControl());
                          map.addControl(
                          new MapboxDirections({
                          accessToken: mapboxgl.accessToken
                          }),
                          'top-left'
                          );
                          MyLocation = [JSON.parse('{{ json_long | escapejs }}'), JSON.parse('{{ json_lat | escapejs }}')]
                          AnotherLocation = [me._map.transform._center.lng,me._map.transform._center.lat];
                          


                          // Aqui carga el mapa
                          map.on('load', function() {
                            


                            var marker = new mapboxgl.Marker({
                              draggable: false
                            })
                            .setLngLat([JSON.parse('{{ json_long | escapejs }}'), JSON.parse('{{ json_lat | escapejs }}')])
                            .addTo(map);
                            
                            
                          });
                          // Aquí termina el load del map    
                          
                        </script>      
                      </div>
                      <br>
                      <br>
                      <br>
                      <br>
                      <br>
                      <br>
              <br>
        </div>
      </div>
      <!-- /#page-content-wrapper -->
  
</div>


    <!-- /#wrapper -->
{%endblock%}

{%block scripts%}



{%endblock%}

templates/usuarios/listado_participantes.html
{%extends 'base/base.html'%}
{%load crispy_forms_tags%}
{% load staticfiles %}

{%block extrastatic%}

<style>
#llegar{
    background-color: rgb(251, 202, 17);
}
body {
  overflow-x: hidden;
  background-color: #e7e5e4;
  
}

#page-content-wrapper {
  min-width: 100vw;
}


#categori{
    color:rgb(39, 117, 148);
}
/* www.proyecto24.org
www.nacionalfinanciera.com.mx */
  #page-content-wrapper {
    min-width: 0;
    width: 100%;
  }

  #wrapper.toggled #sidebar-wrapper {
    margin-left: -15rem;
  }
#card{
  border: rgb(251, 202, 17) 5px solid;
}
/* .loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url('static/imagenes/loading.gif') 50% 50% no-repeat rgb(249,249,249);
    opacity: .8;
} */
h1 {
  font-family: "Avant Garde", Avantgarde, "Century Gothic", CenturyGothic, "AppleGothic", sans-serif;
  font-size: 52px;
  padding: 80px 50px;
  text-align: center;
  text-transform: uppercase;
  text-rendering: optimizeLegibility;
}
h1.elegantshadow {
  color: #131313;
  background-color: #e7e5e4;
  letter-spacing: 0.15em;
  text-shadow: 1px -1px 0 #767676, -1px 2px 1px #737272, -2px 4px 1px #767474, -3px 6px 1px #787777, -4px 8px 1px #7b7a7a, -5px 10px 1px #7f7d7d, -6px 12px 1px #828181, -7px 14px 1px #868585, -8px 16px 1px #8b8a89, -9px 18px 1px #8f8e8d, -10px 20px 1px #949392, -11px 22px 1px #999897, -12px 24px 1px #9e9c9c, -13px 26px 1px #a3a1a1, -14px 28px 1px #a8a6a6, -15px 30px 1px #adabab, -16px 32px 1px #b2b1b0, -17px 34px 1px #b7b6b5, -18px 36px 1px #bcbbba, -19px 38px 1px #c1bfbf, -20px 40px 1px #c6c4c4, -21px 42px 1px #cbc9c8, -22px 44px 1px #cfcdcd, -23px 46px 1px #d4d2d1, -24px 48px 1px #d8d6d5, -25px 50px 1px #dbdad9, -26px 52px 1px #dfdddc, -27px 54px 1px #e2e0df, -28px 56px 1px #e4e3e2;
}
img{
    max-width:430px;
    max-height:330px;
}
</style>
<!-- <script type="text/javascript">
    $(document).ready(function($) {

    $(window).on('load',function(){
      $('.loader').fadeOut('slow',function(){$(this).remove();});
    });
    });
  </script> -->

{%endblock%}


{%block content%}
<div class="loader"></div>
<!-- Page Content -->
<div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
          
  
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              
            </ul>
          </div>
        </nav>
        <br>
        
    
        <div class="container-fluid">
            <!-- <div class="row">
                <div class="col-md-2">
                  
                </div>
                <div class="col-md-8">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <div{% if message.tags == "success" %} class="alert alert-success"
                      {%else%}
                      class="alert alert-danger"
                      {% endif %}>
                      {{ message }}</div>
                        {% endfor %}
                    </ul>
                  {% endif %}
                </div>
                <div class="col-md-2">
                    
                </div>
              </div>	 -->
                  <!-- Mensaje -->
                 

            <div class="row">
              <div  class="col-md-12">
                  
                  <h1 class='elegantshadow'>¡Participa por un iPhone PRO MAX! O vota por tu favorito</h1>
                    <br>
                    <div class="alert alert-info">
                        <h2>
                      <b>COMO VOTAR:</b> Una vez que te hayas registrado, se te generará un folio y aparecerá junto con tu foto, ese folio será tu identidad. <b>Ejemplo:</b> Supongamos que tu folio es el 0100. Tus amigos y allegados tendrán que presionar "votar" justo donde está tu foto, y enviar el mensaje: "MI VOTO ES PARA 0100". Cada mensaje que recibamos será un voto a tu favor.

                        </h2>
                    </div>

                    <br>
                  <br>
              </div>
          </div>
          <!-- fin mensaje -->
                  <br>
                  <br>
                  
            
                    {% load columns %}

                    <div class="row">
                        {% for col in participantes|columns:3 %}
                            <div class="col-md-4">
                                {% for item in col %}
                                <div class="card" style="width: 100%;">
                                  <br>
                                    <h5 class="card-title text-center"><i class="fa fa-star fa-w-16 fa-3x"></i> <b>{{item.num_votos}}</b></h5>
                                  <div align="center">
                                      <img class="card-img-top"   src="{{item.imagen.url}}" alt="Card image cap">
                                  </div>
                                  <div class="card-body">
                                      <h5 class="card-title text-center"><b>{{item.nombre}}</b></h5>
                                      <h5 class="card-title text-center">Folio del participante: <b>{{item.id}}</b></h5>
                                      {%if request.user.is_authenticated%}
                                      <a href="#" style="width: 100%;" data-toggle="modal" data-target="#iniciarSesion{{item.id}}" class="btn btn-primary">Más información <i class="fa fa-plus"></i></a>
                                      {%endif%}
                                    <a href="https://wa.me/5216871235766" style="width: 100%;" class="btn btn-success">Votar   <i class="fa fa-thumbs-up fa-w-16 fa-1x"></i>  <i class="fa fa-whatsapp"></i></a>
                                  </div>
                                </div>
                                <br>
                                {% endfor %}
                            </div><!-- /col-md-4 -->
                        {% endfor %}
                    </div><!-- /row -->
              
                    <br>
                    <br>
                    <br>
            <br>
        </div>
      </div>
      <!-- /#page-content-wrapper -->
  
</div>
{% for i in participantes %}
  <div class="modal fade" id="iniciarSesion{{i.id}}">
      <div class="modal-dialog">
        <div class="modal-content">
          <!-- Modal Header -->
          <div class="modal-header">
            <h4 title="Click aqui para iniciar sesion" style="text-align: center;" class="modal-title text-center">Participante</h4>
            <button  type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <!-- Modal body -->
          <div align="center">
              <img class="card-img-top"   src="{{i.imagen.url}}" alt="Card image cap">
          </div>
        <div class="modal-body">
            <h5 class="card-title text-center">Nombre: <b>{{i.nombre}}</b></h5>
            <h5 class="card-title text-center">Folio: <b>{{i.id}}</b></h5>
            <h5 class="card-title text-center">Teléfono: <b>{{i.telefono}}</b></h5>
            <h5 class="card-title text-center">Teléfono 2: <b>{{i.telefono2}}</b></h5>
            <h5 class="card-title text-center">Red Social: <b>{{i.red_social}}</b></h5>
            <h5 class="card-title text-center">Email: <b>{{i.email}}</b></h5>
            <h5 class="card-title text-center">Localidad: <b>{{i.estado}}, {{i.municipio}}, {{i.colonia}}</b></h5>
        <div style="text-align: center;">
          <button  type="reset" data-dismiss="modal" class="btn btn-success"><i class="fa fa-check"></i> OK!</button>
          <br> 
          <br>
        </div>  
        </div>
        </div>
      </div>
    </div>
{% endfor %}

    <!-- /#wrapper -->
{%endblock%}

{%block scripts%}


{%endblock%}

templates/usuarios/login.html
{%extends 'base/base.html'%}
{%load crispy_forms_tags%}
<style>
#btn2
    {
      background-color: yellow;
      color:black;
      margin-right: 15px;
      width:115px;
    }
</style>
{%block content%}
<br>
<br>
<div class="container col-sm-8">
<form method="post" class="form-signin-heading">
   <h2 class="form-signin-heading" style="text-align: center;">Iniciar sesion</h2>
   {% csrf_token %}
   {{form|crispy}}
   <div style="text-align: center;">
      <button id="btn2" class="btn btn" type="submit" value="Entrar">Entrar</button>
   </div>
   <br>
   <br>
</form>

</div>

{%endblock%}

templates/usuarios/registrar.html
{% extends "base/base.html" %}



{% block head_title %} Registro de Usuario {% endblock %}

{% block content %}
<div class="container col-lg-9 col-md-12">
    <form id="id_frm_registrar" method="POST">
        {%csrf_token%}
        <div id="div_id_correo" class="form-group">
        <br>
        <h4>Registro de Usuario</h4>
            <br>
            <br>
            <label for="id_correo" class="form-control-label">
                E-mail*
            </label>
            <input maxlength="30" id="id_correo" name="email" class="col-lg-9 col-md-12 form-control" type="email">
            <strong id="id_strong_correo" style="color:red;font-size: 11;visibility: hidden;"></strong>
        </div>
        <div  class="form-group">
            <label for="id_nombre" class="form-control-label">Nombre*</label>
            <input maxlength="30" class="col-lg-9 col-md-12 form-control" type="text" name="username" id="id_nombre">
        </div>
        <div class="form-group" >
            <label for="id_contrasena" class="form-control-label">
                Contraseña*
            </label>
            <input maxlength="18" class="col-lg-9 col-md-12 form-control" id="id_contrasena" name="contrasena" type="password">
            <strong id="id_strong_contrasenas" style="color:red;font-size: 11;visibility: hidden;"></strong>
        </div>
        <div style="text-align: center;"class="col-lg-9 col-md-12">
            <button title="Click aqui para guardar"  type="submit" class="btn btn-primary">Registrarse</button>
        </div>
        <br>
        <br>

    </form>
    
</div>

{% endblock %}

templates/usuarios/registro_participantes.html
{%extends 'base/base.html'%}
{% load staticfiles %}

{%block extrastatic%}

<style>
#llegar{
    background-color: rgb(251, 202, 17);
}
body {
  overflow-x: hidden;
  background-color: #e7e5e4;
}

#page-content-wrapper {
  min-width: 100vw;
}


#categori{
    color:rgb(39, 117, 148);
}
/* www.proyecto24.org
www.nacionalfinanciera.com.mx */
  #page-content-wrapper {
    min-width: 0;
    width: 100%;
  }

  #wrapper.toggled #sidebar-wrapper {
    margin-left: -15rem;
  }
#card{
  border: rgb(251, 202, 17) 5px solid;
}
/* .loader {
    position: fixed;
    left: 0px;
    top: 0px;
    width: 100%;
    height: 100%;
    z-index: 9999;
    background: url('static/imagenes/loading.gif') 50% 50% no-repeat rgb(249,249,249);
    opacity: .8;
} */
@keyframes jump {
  0% {
    top: 0;
  }
  50% {
    top: 50px;
  }
  100% {
    top: 0;
  }
}
#arrow-down {
  position: relative;
  margin: 0 auto;
  text-align: center;
  animation: jump 5s infinite;
}
#arrow-down i {
  content: '\f0a8';
  font-family: 'FontAwesome';
  font-size: 80px;
  transition: 0.3s ease-in-out;
}
#arrow-down i:hover {
  opacity: 0.7;
  transition: 0.3s ease-in-out;
}
</style>
<!-- <script type="text/javascript">
    $(document).ready(function($) {

    $(window).on('load',function(){
      $('.loader').fadeOut('slow',function(){$(this).remove();});
    });
    });
  </script> -->

{%endblock%}


{%block content%}
<div class="loader"></div>
<!-- Page Content -->
<div id="page-content-wrapper">

        <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
          
  
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
              
            </ul>
          </div>
        </nav>
        <br>
        <br>
        <br>
    
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                  
                </div>
                <div class="col-md-8">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <div{% if message.tags == "success" %} class="alert alert-success"
                      {%else%}
                      class="alert alert-danger"
                      {% endif %}>
                      {{ message }}</div>
                        {% endfor %}
                    </ul>
                  {% endif %}
                </div>
                <div class="col-md-2">
                    
                </div>
              </div>	
                  <!-- Mensaje -->
            <div class="row">
              <div class="col-md-12">
                
              </div>
          </div>
          <!-- fin mensaje -->
          <div  class="container col-lg-6 col-md-12">
              <div class="alert alert-success" role="alert">
                  <h3>Para poder participar solo tienes que registrarte e invitar a todos tus amigos para que voten por ti. La persona que obtenga más votos el día 15 de septiembre del presente año, será el auténtico ganador del iPhone 11 PRO MAX, con un valor de 37 mil pesos. PUEDE PARTICIPAR CUALQUIER PERSONA DE LA REPÚBLICA MEXICANA.</h3>
                  </div>
                  <div id="arrow-down">
                      <i class="fa fa-chevron-down"></i>
                    </div>  
                    <br>
                     <br>
              <h1 style="text-align: center;">REGÍSTRATE COMO PARTICIPANTE</h1>

              
              
          <form method="POST" enctype="multipart/form-data">
              {%csrf_token%}
              <br>
              <br>
              <br>
                  <div class="form-group" >
                      <label  class="form-control-label">
                          <h3>Nombre completo*</h3>
                      </label>
                      <input  class="col-lg-12 col-md-12 form-control"  name="nombre" type="text" required>
                      <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                  </div>
                  <div class="form-group" >
                      <label  class="form-control-label">
                          <h3>Teléfono*</h3>
                      </label>
                      <input  class="col-lg-12 col-md-12 form-control"  name="telefono" type="number" required>
                      <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                  </div>
                  <div class="form-group" >
                      <label  class="form-control-label">
                          <h3>Teléfono 2*</h3>
                      </label>
                      <input  class="col-lg-12 col-md-12 form-control"  name="telefono2" type="number">
                      <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                      <small id="emailHelp" class="form-text text">Teléfono 2 del participante, es opcional.</small>
                  </div>
                  <div class="form-group" >
                      <label  class="form-control-label">
                          <h3>Email*</h3>
                      </label>
                      <input  class="col-lg-12 col-md-12 form-control"  name="email" type="email">
                      <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                      <small id="emailHelp" class="form-text text">Email del participante, es opcional.</small>
                  </div>
                  <div class="form-group" >
                      <label  class="form-control-label">
                          <h3>Imagen*</h3>
                      </label>
                      <input  class="col-lg-12 col-md-12 form-control" name="imagen" type="file" required>
                      <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                      <small id="emailHelp" class="form-text text">Fotografía del participante, el tamaño de la foto debe ser menor a 4MB.</small>
                  </div>
                  <div class="form-group" >
                      <label  class="form-control-label">
                          <h3>Red Social*</h3>
                      </label>
                      <input  class="col-lg-12 col-md-12 form-control"  name="red_social" type="text">
                      <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                      <small id="emailHelp" class="form-text text">Red Social del participante, es opcional.</small>
                  </div>
                  <div class="form-group">
                      <label for="exampleSelect1"><h3>Estado de la República*</h3> </label>
                      <select name="estado" class="col-lg-9 col-md-12 form-control" id="Select2">
                          {% for i in estados %}
                              <option value="{{i.id}}">{{i.nombre}}</option>
                          {% endfor %}
                      </select>
                    </div>
                    <div class="form-group" >
                        <label  class="form-control-label">
                            <h3>Municipio*</h3>
                        </label>
                        <input  class="col-lg-12 col-md-12 form-control"  name="municipio" type="text" required>
                        <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                    </div>
                    <div class="form-group" >
                        <label  class="form-control-label">
                           <h3>Dirección*</h3>
                        </label>
                        <input  class="col-lg-12 col-md-12 form-control"  name="colonia" type="text" required>
                        <strong  style="color:red;font-size: 11;visibility: hidden;"></strong>
                    </div>
                 
                  
              <div style="text-align: center;">
                  <button  class="btn btn-success" type="submit" value="Entrar"><h3>Registrarte</h3></button>
              </div>
              <br>
              <br>
          </form>
          
      </div>
                
                   
                    
                    
            

        </div>
      </div>
      <!-- /#page-content-wrapper -->
  
</div>


    <!-- /#wrapper -->
{%endblock%}

{%block scripts%}


{%endblock%}